config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "castles#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  resources :castles do
    collection do
      get :my_castles
    end
    resources :bookings, only: [:new, :create]
  end

  resources :bookings, only: [:index, :show, :edit, :update, :destroy]
  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :castle
  belongs_to :user

  validates :start_date, presence: true
  validates :end_date, presence: true

  
end

app/models/castle.rb
class Castle < ApplicationRecord
  belongs_to :user
  has_many_attached :photos

  validates :title, :price, :location, presence: true
  validates :description, length: { minimum: 6 }

  geocoded_by :location
  after_validation :geocode
end

app/models/user.rb
class User < ApplicationRecord
  has_many :bookings, dependent: :destroy
  has_many :castles
  validates :first_name, :last_name, presence: true
  validates :email, :password, presence: true
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create]
  def index
    @bookings = current_user.bookings
    if (@bookings.empty?)
      @message = "No actual bookings"
    end
  end

  def show
    @booking = Booking.find(params[:id])
    @castle = @booking.castle
  end

  def new
    @castle = Castle.find(params[:castle_id])
    @booking = Booking.new(castle: @castle)
  end

  def create
    @booking = current_user.bookings.new(booking_params)
    @castle = Castle.find(params[:castle_id])
    @booking.castle = @castle

    if @booking.save
      redirect_to castle_path(@castle)
    else
      puts @booking.errors.full_messages
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @booking = Booking.find(params[:id])
    if @booking.user == current_user
      @booking.destroy
      redirect_to bookings_path, notice: 'Castle was successfully destroyed.'
    else
      redirect_to booking_path, alert: 'You are not authorized to delete this castle.'
    end
  end

  private

  def booking_params
    params.require(:booking).permit(:castle_id, :start_date, :end_date)
  end
end

app/controllers/castles_controller.rb
class CastlesController < ApplicationController
  def index
    @castles = Castle.all
  end

  def show
    @castle = Castle.find(params[:id])
      @markers = [{
        lat: @castle.latitude,
        lng: @castle.longitude
      }]
  end

  def my_castles
    @castles = current_user.castles
  end

  def new
    @castle = Castle.new
  end

  def create
    @castle = Castle.new(castle_params)
    @castle.user = current_user
    if @castle.save
      redirect_to castle_path(@castle)
    else
      puts @castle.errors.full_messages
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @castle = Castle.find(params[:id])
  end

  def update
    @castle = Castle.find(params[:id])
    if @castle.update(castle_params)
      redirect_to @castle, notice: 'Updated Succesfully!'
    else
      render :edit
    end
  end

  private

  def castle_params
    params.require(:castle).permit(:title, :description, :price, :location, photos: [])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/edit.html.erb
<h1>Edit Booking</h1>

<%= form_for @booking do |f| %>
  <div class="row mb-3">
    <%= f.label :start_date %>
    <%= f.date_field :start_date %>
  </div>

  <div class="row mb-3">
    <%= f.label :end_date %>
    <%= f.date_field :end_date %>
  </div>

  <%= f.submit "Update" %>
<% end %>

app/views/bookings/index.html.erb
<div class="container mt-5">
 <h1 class="">Your bookings</h1>
  <div class="row">
    <% @bookings.each do |booking| %>
      <div class="col-md-4 mb-4">
        <div class="card">
          <div class="card-body">
            <%= cl_image_tag booking.castle.photos[0].key, height: 250, crop: :fill, class: "hero" %>
            <h4 class="card-title text-#fd7e14 "><%= booking.castle.title %></h4>
            <p class="card-text"><strong>Start Date: </strong><%= booking.start_date %></p>
            <p class="card-text"><strong>End Date: </strong><%= booking.end_date %></p>
            <% total_nights = (booking.end_date - booking.start_date).to_i %>
            <% total_price = total_nights * booking.castle.price %>
            <p class="card-text"><strong>Total Nights: </strong><%= total_nights %></p>
            <p class="card-text"><strong>Total Price: </strong><%= total_price %></p>
            <p class="confirmation"><strong>BOOKING CONFIRMED</strong><%= booking.confirmed %></p>
          </div>
        </div>
    </div>
    <% end %>
  </div>
  <%= link_to "Browse castles", castles_path, class: "btn btn-primary" %>
</div>

app/views/bookings/new.html.erb
<div class="container mt-5">
  <h1>New Booking</h1>
  <%= simple_form_for @booking, url: castle_bookings_path(@castle) do |f| %>
    <%= f.input :castle_id, as: :hidden, input_html: { value: @castle.id } %>
    <div class="form-input">
      <%= f.label :first_name %>
      <p><%= current_user.first_name %></p>
    </div>

    <div class="form-input">
      <%= f.label :last_name %>
      <p><%= current_user.last_name %></p>
    </div>

    <div class="form-group">
      <%= f.input :start_date, as: :string, label: "Start date", required: true, input_html:  { data: { controller: "datepicker" } }%>
    </div>

   <div class="form-group">
      <%= f.input :end_date, as: :string, label: "End date", required: true, input_html:  { data: { controller: "datepicker" } }%>
    </div>

  <div class="actions">
    <%= f.submit "Book", class: "btn btn-primary" %>
  </div>
<% end %>

</div>

app/views/bookings/show.html.erb
<div class="container mt-10">
<%= link_to "Back to bookings", bookings_path %>
<h1><%= @booking.castle.title %></h1>


<div class="card w-75">
 <%= cl_image_tag @castle.photo.key, class: "castle-image" %>
      <p><strong>Start Date:</strong><%= @booking.start_date %></p>
      <p><strong>End Date:</strong> <%= @booking.end_date %></p>
      <p><strong>User:</strong> <%= @booking.user.first_name %></p>
      <p><strong>Total Nights:</strong> <%= @booking.total_nights%></p>
      <p><strong>Total Price:</strong> <%= number_to_currency(@booking.total_price)%>
    </div>
    <p><%= link_to "Delete booking", booking_path(@booking), data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' }%>
</div>

app/views/castles/edit.html.erb
<div class="container mt-5">
<h1>Edit castle listing</h1>
<%= simple_form_for(@castle) do |f| %>
  <%= f.input :title %>
  <%= f.input :price %>
  <%= f.input :description %>
  <%= f.input :location %>
  <%= f.label "Castle Photo" %>
  <%= f.file_field :avatar %><br>
  <%= f.submit "Update" %>
<% end %>
</div>

app/views/castles/index.html.erb
<div class="banner" style="background-image: url(./img/castle_banner3.png);">
  <div class="container">

  </div>
</div>

<div class="cards-castles">
  <h1 class="castle-recomend">Find Your Castle</h1>
  <div class="cards">
    <% @castles.each do |castle| %>
    <div class="castle-card">
      <%= cl_image_tag castle.photos.first.key, class: "castle-image" %>
      <h2><%= link_to castle.title, castle_path(castle) %></h2>
      <p><strong>Price:</strong> £<%= castle.price %></p>
      <p><strong>Location:</strong> <%= castle.location %></p>
      <p class="castle-check"><%= link_to "Check this castle", castle_path(castle) %></p>
    </div>
    <% end %>
  </div>
  <div class="add-castle-button">
    <%= link_to "Add new castle", new_castle_path, class: "btn btn-primary" %>
  </div>
</div>

app/views/castles/my_castles.html.erb
 <div class="container mt-5">
 <h1 class="">My castles</h1>
  <div class="row">
    <% @castles.each do |castle| %>
      <div class="col-md-4 mb-4">
        <div class="card">
          <div class="card-body">
            <%= cl_image_tag castle.photos[0].key, height: 250, crop: :fill, class: "hero" %>
            <br>
            <br>
            <h2><%= castle.title %></h2>
                  <p><%= castle.description %></p>
                  <p>Location: <%= castle.location %></p>
          </div>
        </div>
    </div>
    <% end %>
</div>

app/views/castles/new.html.erb
<div class="container mt-5">
<h1>Create castle listing</h1>
<%= simple_form_for(@castle) do |f| %>
  <%= f.input :title %>
  <%= f.input :price %>
  <%= f.input :description %>
  <%= f.input :location %>
  <%= f.input :photos, as: :file, input_html: { multiple: true } %>
  <%= f.submit "List", class: "btn btn-primary" %>
<% end %>
</div>

app/views/castles/show.html.erb
<div class="container mt-5">
<div class="title-container">
  <h1><%= @castle.title %></h1>
  <div class="back-to-container">
<%= link_to "Back to castles", castles_path, class: "btn btn-secondary" %>
</div>
</div>
  <div class="castle-details-card">
    <% if @castle.photos.present? %>
      <div class="image-container">
        <div class="main-image">
          <%= cl_image_tag @castle.photos[0].key, height: 400, crop: :fill, class: "hero" %>
        </div>
        <div class="gallery">
          <% unless @castle.photos.count == 1 %>
            <% @castle.photos.each_with_index do |photo, index| %>
              <% next if index == 0 %>
              <%= cl_image_tag photo.key, height: 196, width: 250, crop: :fill %>
            <% end %>
          <% end %>
    <% else %>
      <%= "No photo available" %>
    <% end %>
        </div>
     </div>
  <div class="details-container">
    <div class="details">
      <p><%= @castle.description %></p>
      <br>
      <p>Hosted by <%= "#{@castle.user.username} - experienced host" %></p>
      <hr>
      <p>Price: <%= "£#{(@castle.price)}/per night" %></p>
      <hr>
    </div>
    <div class="button-container">
      <%= link_to "Book this castle", new_castle_booking_path(@castle), class: "btn btn-primary" %>
    </div>
  </div>
  <p>Location: <%= @castle.location %></p>
  <div style="width: 100%; height: 600px;"
    data-controller="map"
    data-map-markers-value="<%= @markers.to_json %>"
    data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
  </div>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UniqueCastlesApp</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Aboreto&family=Anonymous+Pro:ital,wght@0,400;0,700;1,400;1,700&family=Domine:wght@400..700&family=League+Spartan:wght@100..900&family=Lora:ital,wght@0,400..700;1,400..700&family=Satisfy&display=swap" rel="stylesheet">
  </head>

  <body>
    <div class="content">
      <%= render "shared/navbar" %>
      <%= render "shared/flashes" %>
      <br>
      <main>
        <%= yield %>
      </main>
      <br>
    </div>
  </body>
  <%= render "shared/footer" %>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">

      <!-- Links Column for Contact Us and Help -->
      <div>
        <p class="text">Contact us</p>
        <p class="text">Help</p>
        <br>
        <br>
        <br>
        <p class ="text">©2024 CastleBnB, Inc. </p>
      </div>

      <!-- Address Column on the Far Right -->
      <!-- Using offset to push the column to the right -->
      <div class="info">
        <p class="text">
          Castle BnB<br>
          22 Royal Tower Lane<br>
          Edinburgh, EH1 3FT<br>
          United Kingdom<br>
          Tel: +44 131 555 1234<br>
          Email: contact@castlebnb.co.uk
        </p>
      </div>

</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to castles_path, class: "navbar-brand" do %>
      <img class="logo" src="./img/CastleBnb2.png"/>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "Bookings", bookings_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
          <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar", alt: "dropdown menu" %>
          </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Your castle listings",my_castles_castles_path , class: "dropdown-item" %>
              <%= link_to "Your bookings", bookings_path, class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>